name: Deploy lesha bot

on:
  push:
    branches:
      - main

jobs:
  deploy_lesha:
    name: Deploy lesha
    runs-on: ubuntu-latest
    steps:
    - name: Deploying
      uses: appleboy/ssh-action@master
      with:
        host: 91.227.18.79
        username: tg_romantic_bot
        key: ${{ secrets.SECRET_KEY }}
        port: 22
        script: |
          git -C "/home/tg_romantic_bot/TgRomanticBot" pull
          cd /home/tg_romantic_bot/TgRomanticBot
          docker-compose down
          docker-compose rm -fsv
          docker-compose up -d --build
  deploy_ulya:
    name: Deploy ulya
    runs-on: ubuntu-latest
    steps:
    - name: Deploying
      uses: appleboy/ssh-action@master
      with:
        host: 91.227.18.79
        username: tg_romantic_bot_for_ulya
        key: ${{ secrets.SECRET_KEY_ULYA }}
        port: 22
        script: |
          git -C "/home/tg_romantic_bot_for_ulya/TgRomanticBotForUlya" pull
          cd /home/tg_romantic_bot_for_ulya/TgRomanticBotForUlya
          docker-compose down
          docker-compose rm -fsv
          docker-compose up -d --build